const INIT_DATA = 'INIT_DATA';
const SET_DATA = 'SET_DATA';
const ADD_TO_CART = 'ADD_TO_CART';
const ADD_USER = 'ADD_USER';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const DEL_FROM_CART = 'DEL_FROM_CART';
const EDIT_CART_ITEM_NUM = 'EDIT_CART_ITEM_NUM';
const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
const EMPTY_CART = 'EMPTY_CART';
const UPDATE_CART_DATA_TO_USER = 'UPDATE_CART_DATA_TO_USER';
const UPDATE_USER_CART_DATA_TO_CART = 'UPDATE_USER_CART_DATA_TO_CART';


const Actions = {
    INIT_DATA,
    SET_DATA,
    ADD_TO_CART,
    ADD_USER,
    SET_CURRENT_USER,
    DEL_FROM_CART,
    EDIT_CART_ITEM_NUM,
    REMOVE_CURRENT_USER,
    EMPTY_CART,
    UPDATE_CART_DATA_TO_USER,
    UPDATE_USER_CART_DATA_TO_CART
}
export default Actions 